source activiti.db2.create.engine.sql
source activiti.db2.create.history.sql
source activiti.db2.create.identity.sql
source activiti.h2.create.engine.sql
source activiti.h2.create.history.sql
source activiti.h2.create.identity.sql
source activiti.hsql.create.engine.sql
source activiti.hsql.create.history.sql
source activiti.hsql.create.identity.sql
source activiti.mssql.create.engine.sql
source activiti.mssql.create.history.sql
source activiti.mssql.create.identity.sql
source activiti.mysql.create.engine.sql
source activiti.mysql.create.history.sql
source activiti.mysql.create.identity.sql
source activiti.mysql55.create.engine.sql
source activiti.mysql55.create.history.sql
source activiti.oracle.create.engine.sql
source activiti.oracle.create.history.sql
source activiti.oracle.create.identity.sql
source activiti.postgres.create.engine.sql
source activiti.postgres.create.history.sql
source activiti.postgres.create.identity.sql